language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - stable
  - beta
  - nightly
  - 1.37.0
matrix:
  include:
    - rust: stable
      script:
        - cargo test --no-default-features --verbose
        - cargo test --examples --verbose
  allow_failures:
    - rust: nightly
