language: rust
cache: cargo
before_script:
  - cargo update || true
rust:
  - stable
  - beta
  - nightly
  - 1.31.0
matrix:
  include:
    - rust: stable
      script:
        - cargo test --no-default-features --verbose
        - cargo run --example event --verbose
        - cargo run --example test --verbose
  allow_failures:
    - rust: nightly
