language: rust
cache: cargo
before_script:
- cargo update || true
rust:
  - stable
  - beta
  - nightly
  - 1.20.0
  - 1.27.0
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - rustup component add rustfmt-preview
     script:
      - cargo fmt -- --check
      - cargo build --verbose --all
      - cargo test --verbose --all
  allow_failures:
    - rust: nightly
