language: rust
cache: cargo
install:
  - rustup install nightly --profile default
before_script:
  - cargo update || true
rust:
  - stable
  - beta
  - nightly
  - 1.26.0
matrix:
  include:
    - rust: nightly
      script:
        - cargo +nightly fmt -- --check
        - cargo test --no-default-features --verbose
  allow_failures:
    - rust: nightly
