[package]
name = "ics"
version = "0.1.0"
authors = ["hummingly <31522351+hummingly@users.noreply.github.com>"]
description = "A library for creating iCalendar files as specified in RFC 5545."
license = "MIT OR Apache-2.0"
repository = "https://github.com/hummingly/ics"
readme = "README.md"
keywords = ["iCalendar", "ics", "calendar"]

[features]
default =  ["fast_encoding"]
fast_encoding = ["regex", "lazy_static"]

[dependencies]
regex = { version = "1", optional = true }
lazy_static = { version = "1", optional = true}